prepare tech tests

diff --git a/.github/workflows/dbt-test.yml b/.github/workflows/dbt-test.yml
--- a/.github/workflows/dbt-test.yml
+++ b/.github/workflows/dbt-test.yml
@@ -20,10 +20,13 @@ on:
       dbt-test: # Input to determine if dbt tests should be executed or not
         required: true
         description: 'Skip dbt-test?'
-        type: boolean
+        type: string
       macro-tests: # Input to determine if macro tests should be executed or not
         required: true
-        type: boolean
+        type: string
+      tech-tests:
+        required: true
+        type: string
     outputs: #Outputs for test results for PR comment.
       dbt-test-result: 
         value: ${{ jobs.collect-job-results.outputs.dbt-test-result }}
@@ -382,12 +385,96 @@ jobs:
             db-environments/generated_files/dv4dbt-sa-keys.json
             db-environments/generated_files/profiles.yml
       
+  tech-tests:
+    needs: generate-files
+    runs-on: ubuntu-latest
+    # if success or failure to always execute except in the case of an abortion.
+    if: ${{ (success() || failure()) && inputs.tech-test == 'yes' }}
+
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - uses: actions/setup-python@v4
+      with:
+        python-version: '3.x'
+        
+    - name: install python packages
+      run: |
+        python -m pip install --upgrade pip
+        pip install -r $GITHUB_WORKSPACE/db-environments/techtest/requirements.txt
+
+    # Downloading generated artifacts like profiles.yml
+    - name: Download Artifacts 
+      uses: actions/download-artifact@v4
+      with: 
+        name: my-files-${{ inputs.db_name }}
+        path: db-environments/generated_files
+
+    # Waiting for Exasol to start the server.
+    - name: Wait 60s (Exasol only)
+      if: ${{ inputs.db_name == 'exasol' }}
+      run: sleep 60
+
+    # Building the docker Image from the docker Files for each database.
+    - name: Build ${{ inputs.db_name }} image
+      run: docker build -t dv4dbt-${{ inputs.db_name }} --build-arg DBT_DV4DBT_REVISION=${{ inputs.dv4dbt-revision }} --build-arg DBT_TEST_REVISION=${{ inputs.dv4dbt-test-revision }} --build-arg SSH_PRIVATE_REPO_KEY="${{ secrets.SSH_PRIVATE_REPO_KEY }}" -f $GITHUB_WORKSPACE/db-environments/${{ inputs.db_name }}/Dockerfile .
+
+    - name: Run ${{ inputs.db_name }} container dbt seed
+      if: success() || failure()
+      run: docker run --name dv4dbt-seed-${{ inputs.db_name }} --network host dv4dbt-${{ inputs.db_name }} dbt seed --profiles-dir /user/app/profiles --profile ${{ inputs.db_name }}
+
+    - name: Compare ${{ inputs.db_name }} 
+      if: ${{ inputs.db_name == 'bigquery' }}
+      run: |
+        python $GITHUB_WORKSPACE/db-environments/techtest/testBigQuery.py -i '$GITHUB_WORKSPACE/seeds' -s '$GITHUB_WORKSPACE/db-environments/techtest/schema' -p ${{ vars.BIGQUERY_PROJECT }} -d ${{ vars.BIGQUERY_DATASET }}${{ github.run_id }} -k $GITHUB_WORKSPACE/db-environments/generated_files/dv4dbt-sa-keys.json
+    
+    - name: Compare ${{ inputs.db_name }} 
+      if: ${{ inputs.db_name == 'exasol' }}
+      run: |
+        python $GITHUB_WORKSPACE/db-environments/techtest/testExasol.py -i '$GITHUB_WORKSPACE/seeds' -s '$GITHUB_WORKSPACE/db-environments/techtest/schema' -ho ${{ needs.db-environments.outputs.public_ip }} -p ${{ vars.EXASOL_PORT }} -u ${{ vars.EXASOL_DB_USERNAME }} -psw ${{ secrets.EXASOL_DB_PASSWORD }} -sch ${{ vars.EXASOL_DB_SCHEMA }}
+   
+    - name: Compare ${{ inputs.db_name }} 
+      if: ${{ inputs.db_name == 'postgres' }}
+      run: |
+        python $GITHUB_WORKSPACE/db-environments/techtest/testPostgres.py -i '$GITHUB_WORKSPACE/seeds' -s '$GITHUB_WORKSPACE/db-environments/techtest/schema' -ho ${{ vars.POSTGRES_DB_HOST_START }}${{ github.run_id }}${{vars.POSTGRES_DB_HOST_END}} -p ${{ vars.POSTGRES_PORT }} -u ${{ vars.POSTGRES_DB_USERNAME }} -psw ${{ secrets.POSTGRES_DB_PASSWORD }} -db ${{ vars.POSTGRES_DB_SCHEMA }} -sch ${{ vars.POSTGRES_DB_SCHEMA }}
+    
+    - name: Compare ${{ inputs.db_name }} 
+      if: ${{ inputs.db_name == 'redshift' }}
+      run: |
+        python $GITHUB_WORKSPACE/db-environments/techtest/testRedshift.py -i '$GITHUB_WORKSPACE/seeds' -s '$GITHUB_WORKSPACE/db-environments/techtest/schema' -ho ${{ vars.REDSHIFT_DB_HOST_START }}${{ github.run_id }}${{vars.REDSHIFT_DB_HOST_END}} -p ${{ vars.REDSHIFT_PORT }} -u ${{ vars.REDSHIFT_DB_USERNAME }} -psw ${{ secrets.REDSHIFT_DB_PASSWORD }} -db ${{ vars.REDSHIFT_DB }} -sch ${{ vars.REDSHIFT_DB_SCHEMA }}
+    
+    # - name: Compare ${{ inputs.db_name }} 
+    #   if: ${{ inputs.db_name == 'synapse' }}
+    #   run: |
+    #     python $GITHUB_WORKSPACE/db-environments/techtest/testSynapse.py -i '$GITHUB_WORKSPACE/seeds' -s '$GITHUB_WORKSPACE/db-environments/techtest/schema' -ho ${{ vars.SYNAPSE_SQL_ENDPOINT }} -u ${{ vars.SYNAPSE_DB_USERNAME }} -psw ${{ secrets.SYNAPSE_DB_PASSWORD }} -db ${{ vars.SYNAPSE_DB }} -sch ${{ vars.SYNAPSE_DB_SCHEMA }}
+    
+    - name: Compare ${{ inputs.db_name }} 
+      if: ${{ inputs.db_name == 'snowflake' }}
+      run: |
+        python $GITHUB_WORKSPACE/db-environments/techtest/testSnowflake.py -i '$GITHUB_WORKSPACE/seeds' -s '$GITHUB_WORKSPACE/db-environments/techtest/schema' -a ${{ vars.SNOWFLAKE_ACCOUNT }} -w ${{ vars.SNOWFLAKE_WAREHOUSE }} -u ${{ vars.SNOWFLAKE_USERNAME }} -psw ${{ secrets.SNOWFLAKE_PASSWORD }} -db ${{ vars.SNOWFLAKE_DB }} -sch ${{ vars.SNOWFLAKE_SCHEMA }}
+  
+    - name: Compare ${{ inputs.db_name }} 
+      if: ${{ inputs.db_name == 'databricks' }}
+      run: |
+        python $GITHUB_WORKSPACE/db-environments/techtest/testDatabricks.py -i '$GITHUB_WORKSPACE/seeds' -s '$GITHUB_WORKSPACE/db-environments/techtest/schema' -ho ${{ secrets.DATABRICKS_HOST }} -p ${{ vars.DATABRICKS_PORT }} -path sql/protocolv1/o/${{ needs.db-environments.outputs.databricks_workspace_id }}/${{ needs.db-environments.outputs.databricks_cluster_id }} -t ${{ secrets.DATABRICKS_TOKEN }} -sch ${{ vars.DATABICKS_SCHEMA }}${{ github.run_id }}
+   
+    - name: Compare ${{ inputs.db_name }} 
+      if: ${{ inputs.db_name == 'fabrics' }}
+      run: |
+        python $GITHUB_WORKSPACE/db-environments/techtest/testFabrics.py -i '$GITHUB_WORKSPACE/seeds' -s '$GITHUB_WORKSPACE/db-environments/techtest/schema' -se ${{ secrets.FABRIC_SQL_ENDPOINT_START }}${{ vars.FABRIC_SQL_ENDPOINT_END }} -cid ${{ secrets.TFAUTOMATION_AZURE_CLIENT_ID }} -cs ${{ secrets.AZURE_CLIENT_SECRET}} -tid ${{ secrets.TFAUTOMATION_AZURE_TENANT_ID }} -db ${{ vars.FABRIC_DB }} -sch ${{ vars.FABRIC_SCHEMA }}${{ github.run_id }}
+    
+    - name: Compare ${{ inputs.db_name }} 
+      if: ${{ inputs.db_name == 'oracle' }}
+      run: |
+        python $GITHUB_WORKSPACE/db-environments/techtest/testOracle.py -i '$GITHUB_WORKSPACE/seeds' -s '$GITHUB_WORKSPACE/db-environments/techtest/schema' -ho ${{ vars.ORACLE_DB_HOST_START }}${{ github.run_id }}${{ vars.ORACLE_DB_HOST_END }} -p ${{ vars.ORACLE_DB_PORT }} -s ${{ vars.ORACLE_DB_SERVICE }} -db ${{ vars.ORACLE_DB }} -u ${{ vars.ORACLE_DB_USER }} -psw ${{ needs.db-environments.outputs.oracle_db_password }} -sch ${{ vars.ORACLE_DB_SCHEMA }}
   
   dbt-tests:
     needs: generate-files
     runs-on: ubuntu-latest
     # if success or failure to always execute except in the case of an abortion.
-    if: ${{ (success() || failure()) && inputs.dbt-test }}
+    if: ${{ (success() || failure()) && inputs.dbt-test== 'yes' }}
 
 
     steps:
@@ -448,7 +535,7 @@ jobs:
   dbt-macro-tests:
       needs: generate-files
       runs-on: ubuntu-latest
-      if: ${{ (success() || failure()) && inputs.macro-tests }}
+      if: ${{ (success() || failure()) && inputs.macro-tests == 'yes' }}
           
       steps:
       - name: Checkout
