Added documentation in code

diff --git a/.github/workflows/dbt-test.yml b/.github/workflows/dbt-test.yml
--- a/.github/workflows/dbt-test.yml
+++ b/.github/workflows/dbt-test.yml
@@ -3,21 +3,21 @@ name: 'dbt tests'
 on:
   workflow_call:
     inputs:
-      auto-destroy:
+      auto-destroy: # Destroy ressources for every vaue except 'false' after the tests are finished
         description: 'Auto Destroy: Only "true" will prevent destruction.'
         default: 'true'
         type: string
-      db_name:
+      db_name: # Type of Database that should be tested. E.g. 'synapse', 'postgres'...
         required: true
         default: ''
         type: string
-      dv4dbt-revision:
+      dv4dbt-revision: # Name of the branch in datavault4dbt repositoy that should be tested
         required: true
         type: string
-      macro-tests:
+      macro-tests: # Input to determine if macro tests should be executed or not
         required: true
         type: boolean
-    outputs:
+    outputs: #Outputs for tests results for PR comment.
       dbt-test-result: 
         value: ${{ jobs.collect-job-results.outputs.dbt-test-result }}
       dbt-macro-test-result: 
@@ -56,16 +56,20 @@ jobs:
   db-environments:
     defaults:
       run:
-        working-directory: ./db-environments/${{ inputs.db_name }}
+        working-directory: ./db-environments/${{ inputs.db_name }} # Setting working directory for different databases
     runs-on: ubuntu-latest
-    outputs:
+    outputs: 
+      # Output of IP Adress from Exasol EC2 instance
       public_ip: ${{ steps.tf_output.outputs.public_ip }}
+
+      # Output of Cluster- and Workspace-ID for Databricks. 
       databricks_cluster_id: ${{ steps.tf_output_databricks.outputs.databricks_cluster_id }}
       databricks_workspace_id: ${{ steps.tf_output_databricks.outputs.databricks_workspace_id }}
     steps:
     - name: Checkout
       uses: actions/checkout@v3
 
+    # AWS Login
     - name: Configure AWS Credentials Action For GitHub Actions
       uses: aws-actions/configure-aws-credentials@v1-node16
       with:
@@ -73,6 +77,7 @@ jobs:
         aws-secret-access-key:  ${{ secrets.TFAUTOMATION_AWS_SECRET_ACCESS_KEY }}
         aws-region: eu-west-1
 
+    # Microsoft Azure Login
     - name: 'Az CLI login'
       if: ${{ inputs.db_name == 'synapse' || inputs.db_name == 'fabric'}}
       uses: azure/login@v1
@@ -81,12 +86,14 @@ jobs:
         tenant-id: ${{ secrets.TFAUTOMATION_AZURE_TENANT_ID}}
         subscription-id: ${{ secrets.TFAUTOMATION_AZURE_SUBSCRIPTION_ID }}
 
+    # Google Cloud Login
     - name: 'Authenticate to Google Cloud'
       if: ${{ inputs.db_name == 'bigquery' }}
       uses: 'google-github-actions/auth@v0.4.0'
       with:
         credentials_json: '${{ secrets.DV4DBT_SA_KEYS }}'
 
+    # Setting terraform input variables for different Database Environments.
     - name: Create terraform.tfvars for synapse
       if: ${{ inputs.db_name == 'synapse' }}
       run: |
@@ -138,17 +145,21 @@ jobs:
         terraform_version: 1.8.0
         terraform_wrapper: false
     
+    # Initialize Terraform backend dynamicall with run_id for each database.
     - name: Terraform Init
       run: terraform init -backend-config "key=datavault4dbtenvironments/${{ github.run_id }}/${{ inputs.db_name }}/terraform.state" -backend-config "bucket=scalefree-tf-backend" -backend-config "region=eu-west-1" -backend-config "dynamodb_table=scalefree-tf-lock-backend"
         
+    # Apply Terraform configuration with run_id as input
     - name: Terraform Apply
       run: terraform apply -auto-approve -var="run_id=${{ github.run_id }}"
 
+    # Store Run_id in FIFO SQS when the environment should not be destroyed, to shut down the environment automatically at the End of the day.
     - name: Send message to FIFO SQS
       if: ${{ inputs.auto-destroy == 'false' }}
       run: |
         aws sqs send-message --queue-url ${{ secrets.FIFO_SQS_QUEUE_URL }} --message-body "${{ github.run_id }}/${{ inputs.db_name }}" --message-group-id ${{ inputs.db_name }} --message-deduplication-id ${{ inputs.db_name }}
 
+    # Giving the IP Adress of exasol EC2 instance as output from terraform to GitHub. 
     - name: Terraform Output
       if: ${{ inputs.db_name == 'exasol' }}
       id: tf_output
@@ -156,6 +167,7 @@ jobs:
         echo "public_ip=$(terraform output -json | jq -r .publicIP.value)" >> $GITHUB_OUTPUT
         sleep 30
 
+    # Giving the Cluster- and Workspace-ID of Databricks environment from terraform to GitHub.
     - name: Terraform Output
       if: ${{ inputs.db_name == 'databricks' }}
       id: tf_output_databricks
@@ -163,6 +175,7 @@ jobs:
         echo "databricks_cluster_id=$(terraform output -json | jq -r .databricks_cluster_id.value)" >> $GITHUB_OUTPUT
         echo "databricks_workspace_id=$(terraform output -json | jq -r .databricks_workspace_id.value)" >> $GITHUB_OUTPUT
 
+    # Setup and starting of Exasol environment.
     - name: Setup environment and start Server
       if: ${{ inputs.db_name == 'exasol' }}
       uses: appleboy/ssh-action@v1.0.3
@@ -172,10 +185,10 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY_EXASOL }}
           script: |
               docker run --name dv4dbt-exasol --network host --detach --privileged --stop-timeout 120  exasol/docker-db:8.27.0
-  generate-files:
+  generate-files: # generating and uploading of files needed to connect to the environments.
     needs: db-environments
     runs-on: ubuntu-latest
-    if: success() || failure()
+    if: success() || failure() 
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -318,25 +331,30 @@ jobs:
   dbt-tests:
     needs: generate-files
     runs-on: ubuntu-latest
+    # if success or failure to always execute except in the case of an abortion.
     if: success() || failure()
 
     steps:
     - name: Checkout
       uses: actions/checkout@v3
 
-    - name: Download Artifacts
+    # Downloading generated artifacts like profiles.yml
+    - name: Download Artifacts 
       uses: actions/download-artifact@v3
       with: 
         name: my-files
         path: db-environments/generated_files
 
+    # Waiting for Exasol to start the server.
     - name: Wait 60s
       if: ${{ inputs.db_name == 'exasol' }}
       run: sleep 60
 
+    # Building the docker Image from the docker Files for each database.
     - name: Build ${{ inputs.db_name }} image
       run: docker build -t dv4dbt-${{ inputs.db_name }} --build-arg DBT_DV4DBT_REVISION=${{ inputs.dv4dbt-revision }} --build-arg SSH_PRIVATE_REPO_KEY="${{ secrets.SSH_PRIVATE_REPO_KEY }}" -f $GITHUB_WORKSPACE/db-environments/${{ inputs.db_name }}/Dockerfile .
     
+    # Running all Tests with different Variables.
     - name: Run ${{ inputs.db_name }} container DBT_INCREMENTAL_RUN=0 Variables set to True
       if: success() || failure()
       run: |
@@ -351,7 +369,8 @@ jobs:
       run: |
         docker run --name dv4dbt-v2-i0-${{ inputs.db_name }} --network host -e DBT_INCREMENTAL_RUN=0 dv4dbt-${{ inputs.db_name }} dbt build --profiles-dir /user/app/profiles --profile ${{ inputs.db_name }} -f --vars '{datavault4dbt.set_casing: "lowercase", datavault4dbt.copy_rsrc_ldts_input_columns: False, datavault4dbt.hashkey_input_case_sensitive: False, datavault4dbt.hashdiff_input_case_sensitive: False, datavault4dbt.include_business_objects_before_appearance: False}'
     
-    #For Fabric the schema needs to be empty after the last test. In that case we use an extra variable to delete every object in the schema after the tests.
+    # For Fabric the schema needs to be empty after the last test. In that case we use an extra variable to delete every object in the schema after the tests.
+    # DBT tests checking if it is an fabric environment as well. 
     - name: Run ${{ inputs.db_name }} container DBT_INCREMENTAL_RUN=1 Variables set to False and empty schema
       if: success() || failure()
       run: |
@@ -367,19 +386,23 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
+      # Downloading generated artifacts like profile.yml
       - name: Download Artifacts
         uses: actions/download-artifact@v3
         with: 
           name: my-files
           path: db-environments/generated_files
 
+      # Waiting for Exasol server to start.
       - name: Wait 60s
         if: ${{ inputs.db_name == 'exasol' }}
         run: sleep 60
 
+      # Building docker image from dockerfile for each database.
       - name: Build ${{ inputs.db_name }} image
         run: docker build -t dv4dbt-${{ inputs.db_name }} --build-arg DBT_DV4DBT_REVISION=${{ inputs.dv4dbt-revision }} --build-arg SSH_PRIVATE_REPO_KEY="${{ secrets.SSH_PRIVATE_REPO_KEY }}" -f $GITHUB_WORKSPACE/db-environments/${{ inputs.db_name }}/Dockerfile .
       
+      # Run hardcoded Macro tests.
       - name: Run run-operation is_list --args '{obj}' in ${{ inputs.db_name }} container
         if: success() || failure()
         run: docker run --name dv4dbt-macro-test-01-${{ inputs.db_name }} --network host dv4dbt-${{ inputs.db_name }} dbt run-operation is_list --args '{obj}' -d --profiles-dir /user/app/profiles --profile ${{ inputs.db_name }}
@@ -461,6 +484,8 @@ jobs:
       - name: Run run-operation generate_schema_name in ${{ inputs.db_name }} container
         if: success() || failure()
         run: docker run --name dv4dbt-macro-test-26-${{ inputs.db_name }} --network host dv4dbt-${{ inputs.db_name }} dbt run-operation generate_schema_name -d --profiles-dir /user/app/profiles --profile ${{ inputs.db_name }}
+      
+      # Run different tests for oracle and every other database, because of different syntax in oracle.
       - name: "Run run-operation get_query_results_as_dict --args '{query: select 1}' in ${{ inputs.db_name }} container"
         if: ${{ (success() || failure()) && inputs.db_name != 'oracle' }}
         run: |
@@ -469,6 +494,7 @@ jobs:
         if: ${{ (success() || failure()) && inputs.db_name == 'oracle' }}
         run: |
           docker run --name dv4dbt-macro-test-27-${{ inputs.db_name }} --network host dv4dbt-${{ inputs.db_name }} dbt run-operation get_query_results_as_dict --args '{query: select 1 from dual}' -d --profiles-dir /user/app/profiles --profile ${{ inputs.db_name }}
+      
       - name: "Run run-operation get_standard_string --args '{string_list: abc}' in ${{ inputs.db_name }} container"
         if: success() || failure()
         run: |
@@ -510,10 +536,13 @@ jobs:
       - name: Run run-operation timestamp_format in ${{ inputs.db_name }} container
         if: success() || failure()
         run: docker run --name dv4dbt-macro-test-41-${{ inputs.db_name }} --network host dv4dbt-${{ inputs.db_name }} dbt run-operation timestamp_format -d --profiles-dir /user/app/profiles --profile ${{ inputs.db_name }}
+  
+  # trigger the destruction of environments if set as variable during call, after all tests are done.
   trigger-destroy-environments:
     if: ${{ always() && inputs.auto-destroy != 'false' }} 
     needs: [ dbt-tests, dbt-macro-tests ]
 
+  # Same setup jobs as in the setup of the environments.
     defaults:
       run:
         working-directory: ./db-environments/${{ inputs.db_name }}
@@ -580,21 +609,24 @@ jobs:
     - name: Terraform Init
       run: terraform init -backend-config "key=datavault4dbtenvironments/${{ github.run_id }}/${{ inputs.db_name }}/terraform.state" -backend-config "bucket=scalefree-tf-backend" -backend-config "region=eu-west-1" -backend-config "dynamodb_table=scalefree-tf-lock-backend"
         
+    # destruction of created terraform ressources.
     - name: Terraform Destroy
       run: terraform destroy -auto-approve -var="run_id=${{ github.run_id }}"
 
+    # Job to send the results of tests for better monitoring.
   collect-job-results:
     if: always()
     needs: [ dbt-tests, dbt-macro-tests ]
 
     runs-on: ubuntu-latest
-    outputs:
+    outputs: # defining outputs
       dbt-test-result: ${{ steps.results.outputs.dbt-test-result}}
       dbt-macro-test-result: ${{ steps.results.outputs.dbt-macro-test-result}}
 
     steps:
     - name: Collect results
       id: results
+      # setting output values.
       run: |
         echo "dbt-test-result=${{ needs.dbt-tests.result }}" >> $GITHUB_OUTPUT
         echo "dbt-macro-test-result=${{ needs.dbt-macro-tests.result }}" >> $GITHUB_OUTPUT
