Update dbt-test.yml

diff --git a/.github/workflows/dbt-test.yml b/.github/workflows/dbt-test.yml
--- a/.github/workflows/dbt-test.yml
+++ b/.github/workflows/dbt-test.yml
@@ -453,25 +453,22 @@ jobs:
       run: |
         python ./datavault4dbt-automatic-tests/db-environments/techtest/testBigQuery.py -i './datavault4dbt-automatic-tests/seeds' -s './datavault4dbt-automatic-tests/db-environments/techtest/schema' -p ${{ vars.BIGQUERY_PROJECT }} -d ${{ vars.BIGQUERY_DATASET }}${{ github.run_id }} -k $GITHUB_WORKSPACE/db-environments/generated_files/dv4dbt-sa-keys.json
     
-    - name: Compare Exasol 
+    - name: Compare Exasol
       if: ${{ inputs.db_name == 'exasol' }}
-      run: |
-        python ./datavault4dbt-automatic-tests/db-environments/techtest/testExasol.py -i './datavault4dbt-automatic-tests/seeds' -s './datavault4dbt-automatic-tests/db-environments/techtest/schema' -ho ${{ needs.db-environments.outputs.public_ip }} -p ${{ vars.EXASOL_PORT }} -u ${{ vars.EXASOL_DB_USERNAME }} -psw "${{ secrets.EXASOL_DB_PASSWORD }}" -sch ${{ vars.EXASOL_DB_SCHEMA }}
-        
+      run: if [[ -z "${{ needs.db-environments.outputs.public_ip }}" ]]; then echo "Missing Exasol Host"; exit 1; fi; python ./datavault4dbt-automatic-tests/db-environments/techtest/testExasol.py -i './datavault4dbt-automatic-tests/seeds' -s './datavault4dbt-automatic-tests/db-environments/techtest/schema' -ho "${{ needs.db-environments.outputs.public_ip }}" -p "${{ vars.EXASOL_PORT }}" -u "${{ vars.EXASOL_DB_USERNAME }}" -psw "${{ secrets.EXASOL_DB_PASSWORD }}" -sch "${{ vars.EXASOL_DB_SCHEMA }}"
+
     - name: Compare Postgres
       if: ${{ inputs.db_name == 'postgres' }}
-      run: |
-        python ./datavault4dbt-automatic-tests/db-environments/techtest/testPostgres.py -i './datavault4dbt-automatic-tests/seeds' -s './datavault4dbt-automatic-tests/db-environments/techtest/schema' -ho ${{ vars.POSTGRES_HOST }} -p ${{ vars.POSTGRES_PORT }} -u ${{ vars.POSTGRES_USERNAME }} -psw "${{ secrets.POSTGRES_PASSWORD }}" -db ${{ vars.POSTGRES_DB }} -sch ${{ vars.POSTGRES_SCHEMA }}
-    
+      run: if [[ -z "${{ vars.POSTGRES_HOST }}" ]]; then echo "Missing Postgres Host"; exit 1; fi; python ./datavault4dbt-automatic-tests/db-environments/techtest/testPostgres.py -i './datavault4dbt-automatic-tests/seeds' -s './datavault4dbt-automatic-tests/db-environments/techtest/schema' -ho "${{ vars.POSTGRES_HOST }}" -p "${{ vars.POSTGRES_PORT }}" -u "${{ vars.POSTGRES_USERNAME }}" -psw "${{ secrets.POSTGRES_PASSWORD }}" -db "${{ vars.POSTGRES_DB }}" -sch "${{ vars.POSTGRES_SCHEMA }}"
+
     - name: Compare Redshift
       if: ${{ inputs.db_name == 'redshift' }}
-      run: |
-        python ./datavault4dbt-automatic-tests/db-environments/techtest/testRedshift.py -i './datavault4dbt-automatic-tests/seeds' -s './datavault4dbt-automatic-tests/db-environments/techtest/schema' -ho ${{ vars.REDSHIFT_HOST }} -p ${{ vars.REDSHIFT_PORT }} -u ${{ vars.REDSHIFT_USERNAME }} -psw "${{ secrets.REDSHIFT_PASSWORD }}" -db ${{ vars.REDSHIFT_DB }} -sch ${{ vars.REDSHIFT_SCHEMA }}
+      run: if [[ -z "${{ vars.REDSHIFT_HOST }}" ]]; then echo "Missing Redshift Host"; exit 1; fi; python ./datavault4dbt-automatic-tests/db-environments/techtest/testRedshift.py -i './datavault4dbt-automatic-tests/seeds' -s './datavault4dbt-automatic-tests/db-environments/techtest/schema' -ho "${{ vars.REDSHIFT_HOST }}" -p "${{ vars.REDSHIFT_PORT }}" -u "${{ vars.REDSHIFT_USERNAME }}" -psw "${{ secrets.REDSHIFT_PASSWORD }}" -db "${{ vars.REDSHIFT_DB }}" -sch "${{ vars.REDSHIFT_SCHEMA }}"
+
     - name: Compare Synapse
       if: ${{ inputs.db_name == 'synapse' }}
-      run: |
-        python ./datavault4dbt-automatic-tests/db-environments/techtest/testSynapse.py -i './datavault4dbt-automatic-tests/seeds' -s './datavault4dbt-automatic-tests/db-environments/techtest/schema' -ho ${{ vars.SYNAPSE_HOST }} -u ${{ vars.SYNAPSE_USERNAME }} -psw "${{ secrets.SYNAPSE_PASSWORD }}" -db ${{ vars.SYNAPSE_DB }} -sch ${{ vars.SYNAPSE_SCHEMA }}
-    
+      run: if [[ -z "${{ vars.SYNAPSE_HOST }}" ]]; then echo "Missing Synapse Host"; exit 1; fi; python ./datavault4dbt-automatic-tests/db-environments/techtest/testSynapse.py -i './datavault4dbt-automatic-tests/seeds' -s './datavault4dbt-automatic-tests/db-environments/techtest/schema' -ho "${{ vars.SYNAPSE_HOST }}" -u "${{ vars.SYNAPSE_USERNAME }}" -psw "${{ secrets.SYNAPSE_PASSWORD }}" -db "${{ vars.SYNAPSE_DB }}" -sch "${{ vars.SYNAPSE_SCHEMA }}"
+  
     - name: Compare Snowflake
       if: ${{ inputs.db_name == 'snowflake' }}
       run: |
